### ISSUE TITLE
RSS?

### ISSUE THREAD

**Issue by davesnx** [tomyedwab/www#1]
I enjoyed 2 of your blog posts and I wonder if there's a way to know when you publish a new one, have you thought about adding RSS or any other communication channel? 

Thanks and keep writing :)

**Comment by tomyedwab** [comment]
Thanks! That's a good idea, I'll look into RSS very soon.

You can also follow me on BlueSky: https://bsky.app/profile/tomyedwab.bsky.social (I'll add a link to that as well)

**Comment by tomyedwab** [comment]
Added RSS link in page head and on Post history page.
